# Generated by Django 4.0 on 2021-12-31 17:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('in_stock', models.BooleanField(default=True)),
                ('stock_numbers', models.ImageField(blank=True, default=0, null=True, upload_to='')),
                ('image', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
