# Generated by Django 4.0 on 2021-12-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock_numbers",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
