# Generated by Django 4.0 on 2022-02-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="phone_number",
            field=models.IntegerField(null=True),
        ),
    ]
