# Generated by Django 4.0 on 2022-02-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_wallet_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='promoted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
