# Generated by Django 4.0 on 2022-01-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_partnerprofile_partner"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerprofile",
            name="company_image",
            field=models.ImageField(default="default.png", upload_to="companies/"),
        ),
    ]
