# Generated by Django 4.0 on 2022-01-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_partnerprofile_company_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnerprofile",
            name="company_description",
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="partnerprofile",
            name="company_short_bio",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
