# Generated by Django 4.0 on 2022-02-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_profile_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerprofile",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
