# Generated by Django 4.0 on 2022-02-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_partnerprofile_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnerprofile",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
