# Generated by Django 4.0 on 2022-02-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_partnerprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='street_address1',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
