# Generated by Django 4.0 on 2022-01-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=models.IntegerField(null=True),
        ),
    ]
