# Generated by Django 4.0 on 2022-02-05 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created"]},
        ),
    ]
