# Generated by Django 4.0 on 2022-01-31 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0003_order_client_secret"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="client_secret",
            new_name="stripe_pid",
        ),
    ]
