# Generated by Django 4.0 on 2021-12-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="profile",
            name="second_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
