# Generated by Django 4.0 on 2021-12-31 19:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_rename_name_profile_first_name_profile_second_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="username",
        ),
        migrations.CreateModel(
            name="PartnerProfile",
            fields=[
                ("company_name", models.CharField(blank=True, max_length=50)),
                ("company_website", models.CharField(max_length=200, null=True)),
                (
                    "company_short_bio",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
                ("company_description", models.TextField(null=True)),
                (
                    "social_twitter",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "social_linkedin",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "social_youtube",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "social_website",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "partner",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                    ),
                ),
            ],
        ),
    ]
