# Generated by Django 4.0 on 2021-12-31 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_profile_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerprofile",
            name="username",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
