# Generated by Django 4.0 on 2021-12-31 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_partnerprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerprofile',
            name='username',
        ),
    ]
