# Generated by Django 4.0 on 2022-01-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_remove_partnerprofile_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="partner_application",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
