# Generated by Django 4.0 on 2022-01-05 13:44

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_profile_partner_application"),
    ]

    operations = [
        migrations.CreateModel(
            name="wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("account_number", models.ImageField(upload_to="")),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("street_address1", models.CharField(max_length=80)),
                (
                    "street_address2",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "town_or_city",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("county", models.CharField(blank=True, max_length=80, null=True)),
                ("postcode", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                    ),
                ),
            ],
        ),
    ]
