# Generated by Django 4.0 on 2022-01-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='account_number',
            field=models.IntegerField(max_length=8),
        ),
    ]
