# Generated by Django 4.0 on 2022-01-12 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_alter_partnerprofile_company_description_and_more"),
        ("products", "0003_alter_product_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="owner_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.profile",
            ),
        ),
    ]
