# Generated by Django 4.0 on 2022-02-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_webp_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='webp_image',
        ),
    ]
